name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    timeout-minutes: 360  # จำกัดที่ 6 ชั่วโมง

    steps:
     # ใช้งาน Secret Key
      - name: ใช้งาน Secret Key
        run: |
          Write-Host "Using secret key: ${{ secrets.MY_SECRET_KEY }}"

      # ดาวน์โหลดและติดตั้ง Essentials
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/joyzone/lite_manager_win/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          Start-Process -FilePath "cmd.exe" -ArgumentList "/c Downloads.bat" -NoNewWindow -Wait

      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Check Files
        run: Get-ChildItem -Path scripts -Recurse
     
      - name: Show Current Directory
        run: pwd
     
      - name: Run Setup Script
        run: powershell.exe -ExecutionPolicy Bypass -Command "& {./scripts/setup.ps1}"
          
      - name: Setup Windows Environment
        run: powershell.exe -ExecutionPolicy Bypass -File scripts/setup.ps1

      - name: Optimize Windows Performance
        run: powershell.exe -ExecutionPolicy Bypass -File scripts/optimize.ps1
      
      # เชื่อมต่อกับ LiteManager
      - name: Connect to LiteManager
        run: Start-Process -FilePath "cmd.exe" -ArgumentList "/c show.bat" -NoNewWindow -Wait

      # ใช้ Time Counter
      - name: Time Counter
        run: Start-Process -FilePath "cmd.exe" -ArgumentList "/c loop.bat" -NoNewWindow -Wait

      - name: Keep Windows Running
        run: start /b cmd /c keep_alive.bat

      - name: Random Delay
        run: sleep $((RANDOM % 600))  # หน่วงเวลาแบบสุ่ม (0-600 วินาที)
        
      - name: Auto Restart Workflow
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh auth login --with-token <<< "$GH_TOKEN"
          gh workflow run lite_manager_win_cloud_pc.yml

