name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    timeout-minutes: 360  # จำกัดที่ 6 ชั่วโมง

    steps:
      - name: ใช้งาน Secret Key
        run: |
          Write-Host "Using secret key: ${{ secrets.MY_SECRET_KEY }}"


      - name: Clean Junk Files
        run: |
          echo "Cleaning up junk files..."
          Cleanmgr /sagerun:1
          Remove-Item -Path "C:\Windows\Temp\*" -Force -Recurse
          Remove-Item -Path "$env:TEMP\*" -Force -Recurse


      - name: Optimize System
        run: |
          echo "Optimizing system performance..."
          defrag C: /O
          powercfg -h off
          bcdedit /set disabledynamictick yes


      - name: Optimize Internet Stability
        run: |
          echo "Optimizing network settings..."
          netsh int tcp set global autotuninglevel=normal
          netsh int tcp set global ecncapability=disabled
          netsh winsock reset


      - name: Enable Dark Mode
        run: |
          reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v AppsUseLightTheme /t REG_DWORD /d 0 /f
          reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v SystemUsesLightTheme /t REG_DWORD /d 0 /f


      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))


      - name: Install Program
        run: |
          choco install vscode -y
          choco install discord -y
          $blockbenchUrl = "https://github.com/JannisX11/blockbench/releases/download/v4.12.2/Blockbench_x64_4.12.2.exe"
          $installerPath = "$env:TEMP\Blockbench_x64_4.12.2.exe"
          Invoke-WebRequest -Uri $blockbenchUrl -OutFile $installerPath
          Start-Process -FilePath $installerPath -ArgumentList "/S" -NoNewWindow -Wait


      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/joyzone/lite_manager_win/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          Start-Process -FilePath "cmd.exe" -ArgumentList "/c Downloads.bat" -NoNewWindow -Wait


      - name: Connect to LiteManager
        run: Start-Process -FilePath "cmd.exe" -ArgumentList "/c show.bat" -NoNewWindow -Wait


      - name: Time Counter
        run: Start-Process -FilePath "cmd.exe" -ArgumentList "/c oop.bat" -NoNewWindow -Wait
