name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    timeout-minutes: 360  # จำกัดที่ 6 ชั่วโมง

    steps:
      # ใช้งาน Secret Key
      - name: ใช้งาน Secret Key
        run: |
          Write-Host "Using secret key: ${{ secrets.MY_SECRET_KEY }}"

      # ติดตั้ง Chocolatey (ถ้ายังไม่มี)
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      # ติดตั้ง Discord, Blockbench และ VS Code
      - name: Install Discord, Blockbench, and VS Code
        run: |
          choco install vscode -y
          choco install blockbench -y
          choco install discord -y

      # ดาวน์โหลดและติดตั้ง Essentials
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/joyzone/lite_manager_win/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          Start-Process -FilePath "cmd.exe" -ArgumentList "/c Downloads.bat" -NoNewWindow -Wait

      # เชื่อมต่อกับ LiteManager
      - name: Connect to LiteManager
        run: Start-Process -FilePath "cmd.exe" -ArgumentList "/c show.bat" -NoNewWindow -Wait

      # ใช้ Time Counter
      - name: Time Counter
        run: Start-Process -FilePath "cmd.exe" -ArgumentList "/c loop.bat" -NoNewWindow -Wait
