name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest

    timeout-minutes: 360  # จำกัดที่ 6 ชั่วโมง

    steps:
      # ดึงโค้ดจาก Repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ตรวจสอบไฟล์ที่อยู่ใน Repo
      - name: Check Files
        run: cmd /c dir /s scripts

      # ใช้งาน Secret Key
      - name: ใช้งาน Secret Key
        run: cmd /c echo Using secret key: ${{ secrets.MY_SECRET_KEY }}
          
      # ตั้งค่า Windows Environment
      - name: Setup Windows Environment
        run: cmd /c scripts\setup.ps1

      # ปรับแต่ง Windows ให้ดีขึ้น
      - name: Optimize Windows Performance
        run: cmd /c scripts\optimize.ps1

      # ดาวน์โหลดและติดตั้ง Essentials
      - name: Downloading & Installing Essentials
        run: |
          curl -o Downloads.bat https://gitlab.com/joyzone/lite_manager_win/-/raw/main/Downloads.bat
          cmd /c Downloads.bat

      # เชื่อมต่อ LiteManager
      - name: Connect to LiteManager
        run: cmd /c show.bat

      # ใช้ Time Counter
      - name: Time Counter
        run: cmd /c loop.bat
