name: Windows Cloud PC

on:
  workflow_dispatch:

jobs:
  build:
    name: เริ่มการสร้าง...
    runs-on: windows-latest

    timeout-minutes: 360  # จำกัดที่ 6 ชั่วโมง

    steps:
      - name: ใช้งาน Secret Key
        run: |
          Write-Host "Using secret key: ${{ secrets.MY_SECRET_KEY }}"


      - name: ทำความสะอาดไฟล์ขยะ
        run: |
          echo "ทำความสะอาดไฟล์ขยะ"
          Cleanmgr /sagerun:1
          Remove-Item -Path "C:\Windows\Temp\*" -Force -Recurse
          Remove-Item -Path "$env:TEMP\*" -Force -Recurs


      - name: เพิ่มความเสถียรของอินเตอร์เน็ต
        run: |
          echo "เพิ่มความเสถียรของอินเตอร์เน็ต"
          netsh int tcp set global autotuninglevel=normal
          netsh int tcp set global ecncapability=disabled
          netsh winsock reset


      - name: เปิดใช้งานโหมดมืด
        run: |
          reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v AppsUseLightTheme /t REG_DWORD /d 0 /f
          reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v SystemUsesLightTheme /t REG_DWORD /d 0 /f


      - name: ติดตั้ง Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))


      - name: ติดตั้งทรัพยากร
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/mcfirsting1/my-pc/-/raw/main/lite_manager_win/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          Start-Process -FilePath "cmd.exe" -ArgumentList "/c Downloads.bat" -NoNewWindow -Wait


      - name: เชื่อมต่อกับ LiteManager
        run: Start-Process -FilePath "cmd.exe" -ArgumentList "/c show.bat" -NoNewWindow -Wait


      - name: ระยะเวลาดำเนินการ
        run: Start-Process -FilePath "cmd.exe" -ArgumentList "/c loop.bat" -NoNewWindow -Wait
